### ISSUE TITLE
Folders being too large

### ISSUE THREAD

**Issue by MrBlazzar** [Juicysteak117/MinimalImprovement#10]
Not sure why but the folders, when open that is, seem to be the size of the original server icons instead of the size of the current server icons.

![image](https://user-images.githubusercontent.com/5840012/113862123-00c86400-9776-11eb-9736-4576efcaeadc.png)

**Comment by Juicysteak117** [comment]
Well ain't that annoying. I should hopefully be free by this weekend if I don't get it done sooner then that.

**Comment by Juicysteak117** [comment]
Fixed with latest update.
