### ISSUE TITLE
Discord Update 10/4/2021 issue

### ISSUE THREAD

**Issue by MrBlazzar** [Juicysteak117/MinimalImprovement#11]
Updated my discord today to the october 4th patch and now I have a issue where the servers/folders spacing is all wrong

![image](https://user-images.githubusercontent.com/5840012/136549014-245db75c-aaf3-4d3b-9b2c-9a48bfa3fd49.png)

**Comment by Juicysteak117** [comment]
Should be fixed.

**Comment by MrBlazzar** [comment]
Indeed it is
![image](https://user-images.githubusercontent.com/5840012/136676024-a26f8f55-0ae2-4216-ad29-b00ce9bf0e18.png)

Other then the spacing in folders but that was a minor issue before basically just a annoyance.

**Comment by NeonLightning** [comment]
same problem here

**Comment by Juicysteak117** [comment]
Should be fixed now. Sorry for the delay!
