### ISSUE TITLE
Portraits Larger then should be

### ISSUE THREAD

**Issue by MrBlazzar** [Juicysteak117/MinimalImprovement#12]
Booted up discord today and noticed the portraits are overly large in the right side

![image](https://user-images.githubusercontent.com/5840012/191622773-182985de-a1dc-4e74-93ee-e7521a804627.png)

![image](https://user-images.githubusercontent.com/5840012/191622833-b4d9afff-52d4-423a-ba77-6821b55c67b7.png)

Maybe it's just me but it just seems way larger then it should be.

**Comment by Juicysteak117** [comment]
Yup, update broke it. Easy fix though thankfully.
