### ISSUE TITLE
Holiday Flair avatars bigger then box

### ISSUE THREAD

**Issue by MrBlazzar** [Juicysteak117/MinimalImprovement#13]
So discord allows you to add holiday flair to your avatar icon now. It is bigger then the avatar box is

![image](https://user-images.githubusercontent.com/5840012/206946141-e4fe7b76-5a88-4268-a0f4-68d4c2af341f.png)

![image](https://user-images.githubusercontent.com/5840012/206946167-f27bf81d-4a90-4ecd-bf12-a0e0490979a2.png)

![image](https://user-images.githubusercontent.com/5840012/206946191-d8c071bc-d1d5-40e3-a1ba-e1bc3e2cf95a.png)

Examples.

Not sure if something that can be fixed on your end or something BD has to fix.

**Comment by Juicysteak117** [comment]
Yup, that's my end. Fixed. Thanks for the report.
