### ISSUE TITLE
Server list icon sizes

### ISSUE THREAD

**Issue by JaxxArmstrong** [Juicysteak117/MinimalImprovement#14]
Hello,

Thank you for a great BetterDiscord theme that I've been enjoying for quite some time. However, after the last Discord update the borderless version of the theme won't change the normal sized server list icons to a smaller version.

The current server indicator is however in it's small size. Just the actual server icons that are 'big'.

**Comment by Juicysteak117** [comment]
Sorry for the delay! Should be all fixed now. Let me know if there's any other issues. Glad to hear that you like the theme :)

**Comment by JaxxArmstrong** [comment]
Thank you kindly.
