### ISSUE TITLE
Question only:  Titlebar color

### ISSUE THREAD

**Issue by JaxxArmstrong** [Juicysteak117/MinimalImprovement#15]
Sorry for bothering you, but I'm doing a re-coloring using a secondary 'theme' and I can't seem to find the proper CSS element to re-color the 'titlebar' (see attached image).

When you have time over would you please throw me a life-line?

Thank you again for your most excellent Discord theme.

![Titlebar needs recoloring 1](https://github.com/Juicysteak117/MinimalImprovement/assets/13659704/c0a9e0b5-0203-432c-ad7a-b7d0162c19ec)

**Comment by Juicysteak117** [comment]
Hey, sorry for the late response! Slipped my mind on answering it. Should be .title-31SJ6t I believe. Somewhere around there, play around with inspect element a bit.

**Comment by JaxxArmstrong** [comment]
Thank you. Much appreciated!
