### ISSUE TITLE
Server list icon sizes

### ISSUE THREAD

**Issue by 8techy** [Juicysteak117/MinimalImprovement#16]
After the latest discord update, the icon sizes went back to normal, not shrunk by the theme like they used to be.

**Comment by Juicysteak117** [comment]
Yup, fully aware. They just did a massive code update so this will take a bit to fix, sorry for any delays!

**Comment by Juicysteak117** [comment]
Sorry for the delay. Should be mostly fixed now, at least the really bad ones. I'll keep working on it!
