### ISSUE TITLE
Discord update broke part of the theme

### ISSUE THREAD

**Issue by williamjcm** [Juicysteak117/MinimalImprovement#2]
*Note: I use the borderless version of the theme*

It started happening after an update that my Discord received yesterday (2018-04-28).

Here, it's enabled: ![themeenabled](https://user-images.githubusercontent.com/13572456/39404634-6e2001f0-4b86-11e8-9239-65ccb5fb59f0.png)

Here's a screenshot of Discord's main window: 
![themebroken](https://user-images.githubusercontent.com/13572456/39404656-c776ec32-4b86-11e8-91f1-393086ff2b90.png)
As you can see, the channel and user lists are still using the vanilla styles.

**Comment by Juicysteak117** [comment]
My computer is broken atm and I am awaiting parts in the mail. I will address this problem when I am able. Hopefully no more than a few days. Thanks for reporting.

**Comment by Juicysteak117** [comment]
Problem should be solved thanks to Intrnl's PR. Could've solved it sooner but I didn't want to merge without viewing it first.

**Comment by williamjcm** [comment]
@Juicysteak117 I can confirm it's fixed. Thanks to you both!

**Comment by williamjcm** [comment]
Sorry to disturb you again, @Juicysteak117, but I have another issue, "thanks to" another Discord update that got applied today on my end (hence why I'm replying to this issue).

Here's what Discord looks like with both minimal mode and the theme enabled:
![ThemeEnabled](https://user-images.githubusercontent.com/13572456/39873114-573bf01a-546a-11e8-9a57-70e9582ba080.png)

Here's what it looks like when both are disabled (because only minimal mode has its own issues):
![ThemeDisabled](https://user-images.githubusercontent.com/13572456/39873248-ab00aaa6-546a-11e8-930d-97767022110d.png)

As you can see, there is a grey area at the bottom of the channel and user lists when the theme's enabled. However, what can't be seen is that those lists can't be scrolled anymore when the theme is enabled, and this is troublesome for servers with long channel lists.

**Comment by Juicysteak117** [comment]
I just got that update about 30 minutes ago and am seeing the same issue. I imagine the selectors changed. I'll hopefully fix it tomorrow, assuming that it is as easy as I think it will be.

**Comment by williamjcm** [comment]
Got it.

Thanks for your quick response!

**Comment by Juicysteak117** [comment]
I've updated the theme. It fixes the inability to scroll, but I can't seem to fix the space that now exists. That was the longest-standing issue with the theme and the workaround worked perfectly, but they've changed how it works. I've tested a number of things that haven't worked, but I'll keep testing. 

Leaving the issue open in case anyone has any ideas on what to do with it.

**Comment by williamjcm** [comment]
I still can't scroll the channel list as of now. I tried on the server with the longest channel list I'm part of.

The user list is scrollable again, though. And its grey space sometimes disappear when scrolling.

**Comment by Juicysteak117** [comment]
Oh, whoops. I didn't actually push the change I thought I did. Channel list now should be fixed. The space goes away when scrolling but I need to find a new workaround to force the space to go away even when it isn't scrolling.

**Comment by Juicysteak117** [comment]
The 'ole classic misclick.

**Comment by williamjcm** [comment]
I can confirm the channel list is now scrollable again (I forgot to reload using `Ctrl+R`). Thanks again!

**Comment by williamjcm** [comment]
Sorry to disturb you again, but yet again another bug appeared. Since I didn't change anything in my BD installation, I'd say the bug was caused by another Discord update.

![minimalimprovement_bug](https://user-images.githubusercontent.com/13572456/41496325-5f6b4d86-713d-11e8-9065-bf66735a36e9.PNG)
Now, the channel icons aren't resized, while the display area is smaller.

**Comment by Juicysteak117** [comment]
Just got the update. Problem fixed and the theme has been updated. Thanks for the report!

**Comment by williamjcm** [comment]
You're welcome!

**Comment by williamjcm** [comment]
I don't know if there was a new Discord update, but since I now have an issue that wasn't there yesterday, I'd say there was one.

Like last time, my BetterDiscord installation and plugins weren't changed.

Today' issue is status icons aren't were they should be:
![MisalignedStatus](https://user-images.githubusercontent.com/13572456/41704618-05757772-7537-11e8-98be-3deeb6866414.png)

**Comment by Juicysteak117** [comment]
How bizarre. It's now fixed. Thanks again for the heads up!

**Comment by williamjcm** [comment]
Another issue, related to the one with the server buttons, this time with the new "Home" button: https://gyazo.com/64031301130199b0d9760f77fba81e73

**Comment by Juicysteak117** [comment]
Fixed.

**Comment by williamjcm** [comment]
Discord's frequent updates should focus on making some BD features obsolete, instead of breaking BD themes.

This time, the channel list is affected:
![ChannelList](https://user-images.githubusercontent.com/13572456/42016418-beb4c2fa-7aab-11e8-9c0c-bdac8c4ee193.png)

**Comment by Juicysteak117** [comment]
What's the problem here? I'm not seeing it. I've just restarted my Discord and checked both theme versions and nothing looks astray.

**Comment by williamjcm** [comment]
The channel list was more to the left in the past.

Here's an old screenshot:
![](https://user-images.githubusercontent.com/13572456/39873114-573bf01a-546a-11e8-9a57-70e9582ba080.png)

EDIT: to put it in another way, the channel list now looks like a mix between your theme and Discord's vanilla theme.

**Comment by Juicysteak117** [comment]
Oh now I see the difference. Both themes still have a padding of 8px, so you might want to restart your discord or check if you have any other themes/custom css that are potentially interacting with it.

**Comment by williamjcm** [comment]
I don't have any other themes, nor do I use custom CSS. And plugins aren't the culprits, since there wasn't any changes in the active plugins, nor any of them got updates between before and now.

**Comment by Juicysteak117** [comment]
Did you restart your Discord? The theme should up to date. I've just now re-uploaded the theme and double checked that the padding is at 8px.

**Comment by williamjcm** [comment]
There's still that space on both sides (the left side in this screenshot):
![image](https://user-images.githubusercontent.com/13572456/42076794-e8773c0a-7b76-11e8-96f3-babdc6baca38.png)

**Comment by Juicysteak117** [comment]
I'm not sure what to tell you. I've checked everything and there's no reason that there should be any space there. The margin that you apparently still have has definitely been removed. I slapped on an !important to the element so maybe that will fix your issue. Restart Discord and hopefully it will be fixed?

**Comment by Juicysteak117** [comment]
Ok no it looks that the update was just horribly delayed for me, despite restarting numerous times. Now I'm seeing the issue. I'll fix it ASAP.

**Comment by williamjcm** [comment]
An update broke the theme in the chat area:
![image](https://user-images.githubusercontent.com/13572456/43181408-38adf540-8fdd-11e8-92d0-45604236e530.png)
Also, that update broke other plugins that interacted with that area.

EDIT: I saw you fixed it after I reloaded BetterDiscord. Thanks!

**Comment by williamjcm** [comment]
So, it seems there was a new update, since I now have a bunch of issues that weren't present yesterday (French time).

- The home button's icon is much smaller:
![image](https://user-images.githubusercontent.com/13572456/43243698-2d07f0b2-90a8-11e8-89ef-5c4de44ddaef.png)
- The server name became smaller:
![image](https://user-images.githubusercontent.com/13572456/43243722-44695cdc-90a8-11e8-96ac-cc8d8093af57.png)
- This area at the bottom of the channel list became smaller too:
![image](https://user-images.githubusercontent.com/13572456/43243772-7cbd9d0a-90a8-11e8-8637-11390b503f12.png)
- Text in the userlist became smaller, judging by the empty square's size:
![image](https://user-images.githubusercontent.com/13572456/43243823-b072f0b4-90a8-11e8-9393-af61f4cc48ed.png)
- There's now a bigger space between posts, as if the vanilla theme was used:
![image](https://user-images.githubusercontent.com/13572456/43243890-f61eb0d0-90a8-11e8-98c7-d11cf9cb207b.png)
  - This space is also present in the mentions menu and maybe the pinned messages menu.
- The status buttons are now square (I don't really mind, though, so it's up to you):
![image](https://user-images.githubusercontent.com/13572456/43243911-10c2cd36-90a9-11e8-9e14-40e44313f3e4.png)
  - Also, the status indicators in the "Mutual friends" tab of users' profile became square too.
- There is an old issue with the calendar used in searches, but I always forgot to report it:
![image](https://user-images.githubusercontent.com/13572456/43244451-f9255a34-90aa-11e8-98e2-0591b29e499a.png)

That's all I could find at the moment.

EDIT: the status icons in the friend list also became square: 
![image](https://user-images.githubusercontent.com/13572456/43245464-a818c992-90ae-11e8-824a-6cedd8a9d665.png)

EDIT 2: the typing indicators are also smaller, and don't fit the three animated dots anymore:
![image](https://user-images.githubusercontent.com/13572456/43246364-b849dcae-90b1-11e8-89b3-215f3afa8716.png)

**Comment by Juicysteak117** [comment]
Nice! Thanks for the list. This update broke a million things. I'll work towards fixing it later today.
