### ISSUE TITLE
Issue with latest update

### ISSUE THREAD

**Issue by MrBlazzar** [Juicysteak117/MinimalImprovement#5]
Getting a issue with folders that I didn't have till a recent update to discord:

![image](https://user-images.githubusercontent.com/5840012/78837755-b70e3780-79c2-11ea-8d92-d3cd0acdd093.png)

Any chance there is a quick fix or something that can be fixed in the theme?

Thanks.

**Comment by Juicysteak117** [comment]
Oh weird. I'll try to see about getting it fixed ASAP.

**Comment by Juicysteak117** [comment]
Alright a fix is live and should be working. Let me know if it is still broken!

**Comment by MrBlazzar** [comment]
It did fix the worst of the issues still a little increase in it but otherwise fixed it mostly. Examples of the current version

![image](https://user-images.githubusercontent.com/5840012/78928705-16c21c80-7a6f-11ea-8049-dca9a84ed45e.png)

![image](https://user-images.githubusercontent.com/5840012/78928715-1a55a380-7a6f-11ea-9066-4521b4413a81.png)

**Comment by Juicysteak117** [comment]
Ah damn it. I had made a change but wasn't able to fully test it. I think my numbers were off though. I'll fix it in the morning.

**Comment by Juicysteak117** [comment]
Sorry this took a while! I forgot about it. It should be good now right?

**Comment by MrBlazzar** [comment]
It is indeed fixed. Thanks for looking into and fixing the issue.
