### ISSUE TITLE
Server issue with updates.

### ISSUE THREAD

**Issue by MrBlazzar** [Juicysteak117/MinimalImprovement#7]
Hello,

Apologies for only ever coming around with issues but after doing a recent update I'm having a issue with servers not fitting the bar anymore as you can see by this image:

![image](https://user-images.githubusercontent.com/5840012/112692132-d4971400-8e54-11eb-87d2-41b04c25f6e1.png)

Any help would be greatly appreciated.

**Comment by MrBlazzar** [comment]
This is with the MinimalImprovementBorderless version forgot to mention.

**Comment by Juicysteak117** [comment]
No worries, I appreciate the heads up! Just updated it and it should be good now.
