### ISSUE TITLE
Some status indicators have wrong shape

### ISSUE THREAD

**Issue by OdinGitDat** [Juicysteak117/MinimalImprovement#9]
Some status indicators have an oval shape instead of the normal shape.

![example](https://media.discordapp.net/attachments/353200873020850177/829046342910607380/unknown.png)

**Comment by Krulvis** [comment]
They remain this shape sometimes after someone has been typing (which expands the indicator to this oval shape)

**Comment by Juicysteak117** [comment]
Unsure of how to reproduce this. Which status indicators are affected?

**Comment by OdinGitDat** [comment]
Happens only to the status indicators in server member lists.

**Comment by Juicysteak117** [comment]
Which theme is it? Is this with or without borders? Any other relevant themes or plugins that might be affecting things? I'm not seeing this at all on my end.

**Comment by OdinGitDat** [comment]
I've disabled all my plugins and it still occurs, I'm using the bordered variant. It happens after the typing indicator with the 3 dots occurs. When the dots disappear the indicator shape stays oval.

**Comment by Krulvis** [comment]
> Happens only to the status indicators in server member lists.
> I've disabled all my plugins and it still occurs, I'm using the bordered variant. It happens after the typing indicator with the 3 dots occurs. When the dots disappear the indicator shape stays oval.

Same thing happens in DM user list. I am also using the bordered variant. Also happens on my own marker in bottom left:
![bug_discord](https://user-images.githubusercontent.com/21366036/114871012-1f270300-9df9-11eb-8ac3-e4539ffbb4d2.png)

**Comment by Juicysteak117** [comment]
Hmm, I really don't have a clue what's going on with it. I'll see if I can play around with it or something but this is bizarre.
